### PR TITLE
WINUI-3164 Add UG document for the classic 3D-charts

### PR DESCRIPTION
**Pull request by naveenkumar-sanjeevirayan**
Added UG document for the classic 3D-charts.

### CODE REVIEW

**Comment by naveenkumar-sanjeevirayan** [comment]
rebuild

**Review by MuneeshKumarG — APPROVED** [review]
This is fine

**Comment by naveenkumar-sanjeevirayan** [comment]
rebuild

**Comment by naveenkumar-sanjeevirayan** [comment]
rebuild

**Comment by kannans24** [comment]
rebuild

**Review by MuneeshKumarG — APPROVED** [review]
This is fine

**Pull request merged**
